use std::{fmt, str};

/// All books excluding number prefix.
///
/// For example, there is only 'kings' instead of '1 kings' and '2 kings'. Using 'john' means '1
/// john', '2 john', and '3 john' can all be removed.
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum BookToken {
    // Old Testament
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    Samuel,
    Kings,
    Chronicles,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    SongOfSolomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,

    // New Testament
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    Corinthians,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    Thessalonians,
    Timothy,
    Titus,
    Philemon,
    Hebrews,
    James,
    Peter,
    Jude,
    Revelation,
}

impl fmt::Display for BookToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = match self {
            BookToken::Genesis => "genesis",
            BookToken::Exodus => "exodus",
            BookToken::Leviticus => "leviticus",
            BookToken::Numbers => "numbers",
            BookToken::Deuteronomy => "deuteronomy",
            BookToken::Joshua => "joshua",
            BookToken::Judges => "judges",
            BookToken::Ruth => "ruth",
            BookToken::Samuel => "samuel",
            BookToken::Kings => "kings",
            BookToken::Chronicles => "chronicles",
            BookToken::Ezra => "ezra",
            BookToken::Nehemiah => "nehemiah",
            BookToken::Esther => "esther",
            BookToken::Job => "job",
            BookToken::Psalms => "psalms",
            BookToken::Proverbs => "proverbs",
            BookToken::Ecclesiastes => "ecclesiastes",
            BookToken::SongOfSolomon => "songofsolomon",
            BookToken::Isaiah => "isaiah",
            BookToken::Jeremiah => "jeremiah",
            BookToken::Lamentations => "lamentations",
            BookToken::Ezekiel => "ezekiel",
            BookToken::Daniel => "daniel",
            BookToken::Hosea => "hosea",
            BookToken::Joel => "joel",
            BookToken::Amos => "amos",
            BookToken::Obadiah => "obadiah",
            BookToken::Jonah => "jonah",
            BookToken::Micah => "micah",
            BookToken::Nahum => "nahum",
            BookToken::Habakkuk => "habakkuk",
            BookToken::Zephaniah => "zephaniah",
            BookToken::Haggai => "haggai",
            BookToken::Zechariah => "zechariah",
            BookToken::Malachi => "malachi",
            BookToken::Matthew => "matthew",
            BookToken::Mark => "mark",
            BookToken::Luke => "luke",
            BookToken::John => "john",
            BookToken::Acts => "acts",
            BookToken::Romans => "romans",
            BookToken::Corinthians => "corinthians",
            BookToken::Galatians => "galatians",
            BookToken::Ephesians => "ephesians",
            BookToken::Philippians => "philippians",
            BookToken::Colossians => "colossians",
            BookToken::Thessalonians => "thessalonians",
            BookToken::Timothy => "timothy",
            BookToken::Titus => "titus",
            BookToken::Philemon => "philemon",
            BookToken::Hebrews => "hebrews",
            BookToken::James => "james",
            BookToken::Peter => "peter",
            BookToken::Jude => "jude",
            BookToken::Revelation => "revelation",
        };
        write!(f, "{}", text)
    }
}

#[derive(thiserror::Error, miette::Diagnostic, Debug)]
#[error("Unexpected book token")]
pub struct UnexpectedBookToken {
    #[source_code]
    src: String,
}

impl str::FromStr for BookToken {
    type Err = UnexpectedBookToken;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Genesis" => Ok(BookToken::Genesis),
            "Exodus" => Ok(BookToken::Exodus),
            "Leviticus" => Ok(BookToken::Leviticus),
            "Numbers" => Ok(BookToken::Numbers),
            "Deuteronomy" => Ok(BookToken::Deuteronomy),
            "Joshua" => Ok(BookToken::Joshua),
            "Judges" => Ok(BookToken::Judges),
            "Ruth" => Ok(BookToken::Ruth),
            "Samuel" => Ok(BookToken::Samuel),
            "kings" | "Kings" => Ok(BookToken::Kings),
            "Chronicles" => Ok(BookToken::Chronicles),
            "Ezra" => Ok(BookToken::Ezra),
            "Nehemiah" => Ok(BookToken::Nehemiah),
            "Esther" => Ok(BookToken::Esther),
            "Job" => Ok(BookToken::Job),
            "Psalms" => Ok(BookToken::Psalms),
            "Proverbs" => Ok(BookToken::Proverbs),
            "Ecclesiastes" => Ok(BookToken::Ecclesiastes),
            // TODO: Add tests for multi-word books
            "Song of Solomon" => Ok(BookToken::SongOfSolomon),
            "Isaiah" => Ok(BookToken::Isaiah),
            "Jeremiah" => Ok(BookToken::Jeremiah),
            "Lamentations" => Ok(BookToken::Lamentations),
            "Ezekiel" => Ok(BookToken::Ezekiel),
            "Daniel" => Ok(BookToken::Daniel),
            "Hosea" => Ok(BookToken::Hosea),
            "Joel" => Ok(BookToken::Joel),
            "Amos" => Ok(BookToken::Amos),
            "Obadiah" => Ok(BookToken::Obadiah),
            "Jonah" => Ok(BookToken::Jonah),
            "Micah" => Ok(BookToken::Micah),
            "Nahum" => Ok(BookToken::Nahum),
            "Habakkuk" => Ok(BookToken::Habakkuk),
            "Zephaniah" => Ok(BookToken::Zephaniah),
            "Haggai" => Ok(BookToken::Haggai),
            "Zechariah" => Ok(BookToken::Zechariah),
            "Malachi" => Ok(BookToken::Malachi),
            "Matthew" => Ok(BookToken::Matthew),
            "Mark" => Ok(BookToken::Mark),
            "Luke" => Ok(BookToken::Luke),
            "John" => Ok(BookToken::John),
            "Acts" => Ok(BookToken::Acts),
            "Romans" => Ok(BookToken::Romans),
            "Corinthians" => Ok(BookToken::Corinthians),
            "Galatians" => Ok(BookToken::Galatians),
            "Ephesians" => Ok(BookToken::Ephesians),
            "Philippians" => Ok(BookToken::Philippians),
            "Colossians" => Ok(BookToken::Colossians),
            "Thessalonians" => Ok(BookToken::Thessalonians),
            "Timothy" => Ok(BookToken::Timothy),
            "Titus" => Ok(BookToken::Titus),
            "Philemon" => Ok(BookToken::Philemon),
            "Hebrews" => Ok(BookToken::Hebrews),
            "James" => Ok(BookToken::James),
            "Peter" => Ok(BookToken::Peter),
            "Jude" => Ok(BookToken::Jude),
            "Revelation" => Ok(BookToken::Revelation),
            other => Err(UnexpectedBookToken {
                src: other.to_string(),
            }),
        }
    }
}
